---
- name: NFS server setup on CentOS
  hosts: centos
  become: true
  vars:
    export_path: /var/nfs_shared

  tasks:
    - name: Ensure NFS and firewall packages are present
      package:
        name:
          - nfs-utils
          - firewalld
        state: present

    - name: Ensure firewalld is running and enabled
      service:
        name: firewalld
        state: started
        enabled: true

    - name: Ensure NFS service is enabled and started
      service:
        name: nfs-server
        state: started
        enabled: true

    - name: Ensure export directory exists with required ownership/permissions
      file:
        path: "{{ export_path }}"
        state: directory
        owner: nobody
        group: nobody
        mode: "0777"

    - name: Deploy /etc/exports with our share
      template:
        src: ../templates/exports.j2
        dest: /etc/exports
        owner: root
        group: root
        mode: "0644"
      notify: Reload NFS exports

    - name: Open TCP 2049 in firewalld (required by enunciado)
      ansible.posix.firewalld:
        port: 2049/tcp
        permanent: true
        immediate: true
        state: enabled

  handlers:
    - name: Reload NFS exports
      command: exportfs -ra
